### ISSUE TITLE
[todo] Back Propagation + Hill-Climbing 

### ISSUE THREAD

**Issue by pond7897** [pond7897/Back-Propagation-Hill-Climbing#1]
- [ ] ต้องเข้าใจทฤษฎี Back propagation , Hill-climbing และการนำมาผสานกัน ก่อน
- [ ] เข้า Science direct หาข้อมูลเกี่ยวกับ back propagation + 
- [ ] ถ้าลอง Hill-Climbing + Electre iii ว่าสามารถทำได้หรือไม่
- [ ] หาวิธีการที่ใหม่กว่า back propagation + Hill-climbing 
- [ ] แนวทางที่ 1 (back propagation + Hill-climbing(ข้างในใส่ Electre iii))
- [ ] แนวทางที่ 2 หาจุดอ่อนของ back propagation + Hill-climbing 

<img width="467" alt="image" src="https://github.com/user-attachments/assets/2b07caad-52b9-4271-bf65-c309650830a7">
